### ISSUE TITLE
Thyristor BT169 in Digital Output Circuit

### ISSUE THREAD

**Issue by rjtphate7** [TheDIYGuy999/Mega_PLC#1]
Hey TheDIYGuy999,
The purpose of thyristor BT169 in digital output circuit is quite unclear to me, can you explain?
I have simulated and found it ON irrespective of input to optocoupler

**Comment by TheDIYGuy999** [comment]
It does the output short circuit protection, which is triggered at about 0.9A.
The nominal output current is 0.5A

**Comment by rjtphate7** [comment]
Any suggestions in case I wish to increase the nominal output current to 2 A?

**Comment by TheDIYGuy999** [comment]
0.5A is standard for PLC digital outputs. If you want more, I recommend to use a relay, which is controlled by the PLC output.

**Comment by rjtphate7** [comment]
**Thanks for the suggestion**
